name: Nearkick CI

on:
  pull_request:
    branches: [main, dev]

jobs:
  test_contract:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./contract
    steps:
      - uses: actions/checkout@v2
      - run: cargo test
  test_client:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.16.0
      - run: npm i
      - run: npm test
