name: Nearkick CI

on:
  pull_request:
    branches: [main, dev]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm run contract:test
      - run: npm run client:test
